### ISSUE TITLE
how to trace a target program foreground?

### ISSUE THREAD

**Issue by delphi0127** [MarioVilas/winappdbg#14]
when use 08_traceing.py, the target program is running backgroud. For example, when trace calc.exe, I can't find the dialog of calc, how can I see it?

**Comment by MarioVilas** [comment]
There is no concept of running programs "in the background" in Windows, really. What's probably happening is that execution is much slower when tracing so you have to wait for the window to show up...

**Comment by delphi0127** [comment]
Hi, MarioVilas:
 
I trace calc.exe with 08_tracing.py again and agian, every trace spends about 24 hours, and in the end of every trace, the dialog of calc.exe didn't show up, see attachment.
 
thanks for answer.
 
delphi







At 2016-10-08 18:57:07, "Mario Vilas" <notifications@github.com> wrote:


There is no concept of running programs "in the background" in Windows, really. What's probably happening is that execution is much slower when tracing so you have to wait for the window to show up...

**Comment by MarioVilas** [comment]
I'm afraid I don't see any attachment...

**Comment by delphi0127** [comment]
here is result.







At 2016-10-11 07:15:53, "zy" <delphi0127@163.com> wrote:

Hi, MarioVilas:
 
I trace calc.exe with 08_tracing.py again and agian, every trace spends about 24 hours, and in the end of every trace, the dialog of calc.exe didn't show up, see attachment.
 
thanks for answer.
 
delphi







At 2016-10-08 18:57:07, "Mario Vilas" <notifications@github.com> wrote:


There is no concept of running programs "in the background" in Windows, really. What's probably happening is that execution is much slower when tracing so you have to wait for the window to show up...

**Comment by MarioVilas** [comment]
You need to email me directly or log in to Github, replying to Github's emails will get attachments filtered out.
