### ISSUE TITLE
GitHub / SourceForge Confusion

### ISSUE THREAD

**Issue by flowztul** [MarioVilas/winappdbg#16]
Hi,I noticed that the "old" SourceForge page is still up, and also used for some stuff such as documentation and downloads. However, the download links for version 1.6 in the README on GitHub do not work for me at the moment, SourceForge complains that it cannot find the files. Would it be possible to upload the 1.6 Release Installers to GitHub as well, and maybe also move the documentation to over? This may reduce some confusion for new users that try to get the latest version and documentation.

**Comment by MarioVilas** [comment]
You're absolutely right, I will do this.
