### ISSUE TITLE
need to redefine some functions related to window DC

### ISSUE THREAD

**Issue by dodaeche** [MarioVilas/winappdbg#18]
The winappdbg win32 api wrapper defines GetDC, GetWindowDC and ReleaseDC functions as ctypes.windll.gdi32.GetDC. The functions are not exported in gdi32 but in user32. Seems to be need change to ctypes.windll.user32.GetDC. Tested on Windows 10 x64. Thanks MarioVilas.

**Comment by MarioVilas** [comment]
You're right. I guess they were working accidentally in older versions of Windows (import redirections? who knows).
