### ISSUE TITLE
download installer links not works!

### ISSUE THREAD

**Issue by Karaulov** [MarioVilas/winappdbg#19]
download installer links not works!

**Comment by MarioVilas** [comment]
There is no installer anymore. Now you download the sources and run install.bat.

**Comment by MarioVilas** [comment]
Now I see what you mean, the docs at ReadTheDocs are the old ones for some reason. Trying to fix it now.

**Comment by MarioVilas** [comment]
Branch name was wrong, the RTD scripts just failed silently and used an older version of the sources. Fixed now.
