### ISSUE TITLE
Getting Process Name from Event Object

### ISSUE THREAD

**Issue by debasishm89** [MarioVilas/winappdbg#20]
How can I get process name from EventObject , like we do 

event.get_process() ?

**Comment by Crapula-Alligator** [comment]
You can do `event.get_process().get_filename()`, or if you want to be more fancy:

```
process = event.get_process()
name = process.get_filename()
print "Process: %s" % name
```

**Comment by MarioVilas** [comment]
You can do `event.get_process().get_filename()`, or if you want to be more fancy:

```
process = event.get_process()
name = process.get_filename()
print "Process: %s" % name
```

**Comment by debasishm89** [comment]
Thanks you very much Mario. This is what I wanted!

**Comment by MarioVilas** [comment]
You're welcome! :)
