### ISSUE TITLE
Getting Stack Trace with Microsoft Symbols

### ISSUE THREAD

**Issue by debasishm89** [MarioVilas/winappdbg#26]
Hi,

I would like to know if I can configure winappdbg with MS symbol server so that in an app crash detail report I get stack trace with actual MS symbol ? 

crash = Crash(event)
crash.fetch_extra_data(event)
details = crash.fullReport(bShowNotes=True)

Thanks in Advance,

**Comment by MarioVilas** [comment]
Hi!

Provided nothing broke in recent versions (they keep changing the DLL location) if you have installed the Microsoft SDK, you should get symbols for free. You have to configure the corresponding environment variable just like you would with Microsoft's WinDbg.

To quickly test if the symbol support is working correctly, install winappdbg using the provided install.bat script. After installing it will launch a short series of basic tests to see what support you do and do not have in that machine.

Cheers!
/Mario

**Comment by debasishm89** [comment]
Thanks for your quick response. 

It says : Testing WinDbg integration...   FAIL: WinDbg not found 

I actually have not installed Microsoft SDK. I just taken stand alone version of Windbg. Is there any way I can mention the windbg or dbghelp location/path in winappdbg ? so that it can use that. ?

**Comment by debasishm89** [comment]
Resolved the issue by copying windbg to 

C:\Users\someone\Desktop\Debugging Tools for Windows (x86)

Thanks,

**Comment by MarioVilas** [comment]
Reopening since it'd be better if WinAppDbg could autodetect dbghelp.dll in the newer locations.
