### ISSUE TITLE
The inheritance of read function in TextPattern does not pass parameters properly

### ISSUE THREAD

**Issue by jackyzy823** [MarioVilas/winappdbg#27]
https://github.com/MarioVilas/winappdbg/blob/0eb85090873cc0f927085fd9be6e18699a91b8ff/winappdbg/search.py#L248

it should be 
```
data = super(TextPattern, self).read(process, address, size)
```

<del>and also meet the same problem in #11 .</del> it is fixed in 0bab9130f93dff68b9da3d443b5bc7e32e5d29f3. (i'm using v1.5 from PyPi.)

**Comment by MarioVilas** [comment]
Thanks for the bug report! Fixed now :)
