### ISSUE TITLE
Stack argument order is wrong on amd64

### ISSUE THREAD

**Issue by ChrisDietrich** [MarioVilas/winappdbg#30]
For 64-bit Windows, the first four arguments are passed in registers, the rest is passed via the stack (https://msdn.microsoft.com/en-us/library/zthk2dkh.aspx). winappdbg (most recent master branch) seems to parse the stack arguments in the wrong order (also versions 1.5 and 1.6 are affected, I think). I will propose a pull request with a fix. 

Note that this only affects breakpoints/hooks for functions with more than 4 arguments, for example the Windows API function RegQueryValueExW(). A minimal test case could use the following C code with a Hook on RegQueryValueExW() and the arguments data and datalen contain erroneous values (unless the fix is applied):
```
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main()
{
    HKEY CH;
    BYTE* data;
    DWORD datalen;
    datalen = 100;
    DWORD vtype;

    data = malloc(100);
    printf("data    @0x%016x\n", data);
    printf("datalen @0x%016x\n", datalen);

    if(RegOpenKeyW(HKEY_LOCAL_MACHINE, L"Software\\Microsoft\\Windows\\CurrentVersion\\Run", &CH) != 0)
    {
        printf("Error - RegOpenKey\n");
        system("PAUSE");
        return -1;
    }
    if(RegQueryValueExW(CH, L"VBoxTray", NULL, &vtype, data, &datalen) != 0)
    {
        printf("Error - RegQueryValueExW\n");
        system("PAUSE");
        return -1;
    }
    printf("data=%s\n", data);
    RegCloseKey(CH);
    return 0;
}
```

**Comment by MarioVilas** [comment]
Thanks! :)

**Comment by ChrisDietrich** [comment]
Cool, thank you for incorporating the fix so quickly! :) By the way, winappdbg is a pretty great tool.
