### ISSUE TITLE
SHELLEXECUTEINFOA, SHELLEXECUTEINFOW

### ISSUE THREAD

**Issue by yyinhai** [MarioVilas/winappdbg#32]
Hello, thanks for your great work, and it seems that you forgot to split SHELLEXECUTEINFO and LPSHELLEXECUTEINFO to A/W types, which defined in shell32.py: line 176, 201, so that ShellExecuteExA & ShellExecuteExW can't work fine.

**Comment by MarioVilas** [comment]
Hi! That was indeed a silly bug :D thanks for the report!
