### ISSUE TITLE
[question] Can I attach process at starting time?

### ISSUE THREAD

**Issue by kismp123** [MarioVilas/winappdbg#54]
I have a program which I want to test.
It starts another program when it recieve packet.
So I want to attach program when it starts.

Can you give me some example ?
Thanks

**Comment by MarioVilas** [comment]
Hi!

Basically you have two ways.

One is if you are starting the program yourself from the debugger, using the bFollow flag.

Change the first example here: https://winappdbg.readthedocs.io/en/latest/Debugging.html#example-1-starting-a-new-process-and-waiting-for-it-to-finish

Using the bFollow flag: https://pythonhosted.org/winappdbg/winappdbg.debug.Debug-class.html#execv

So it would look like this:
```
from winappdbg import Debug

import sys

# Instance a Debug object.
debug = Debug()
try:

    # Start a new process for debugging.
    debug.execv( sys.argv[ 1 : ], bFollow = True )

    # Wait for the debugee to finish.
    debug.loop()

# Stop the debugger.
finally:
    debug.stop()
```

This way any new process created by your target will also be debugged.

Your second option is a lot more complicated. Auto-following does not work when you attach to a process that has already been started. That means you have to detect the calls to CreateProcessW using a hook, change the parameters to allow debugging, then get the new PID from the return value. (This means you have to use both preCB and postCB). This is a lot more complicated so I won't give a quick example here, but you can read up more on hooks here:

https://winappdbg.readthedocs.io/en/latest/Debugging.html#example-12-hooking-a-function
https://pythonhosted.org/winappdbg/winappdbg.breakpoint._BreakpointContainer-class.html#hook_function
https://parsiya.net/blog/2017-11-11-winappdbg-part-2-function-hooking-and-others/#10-basic-hooking-with-debug-hook-function

Hope that helps! :)

**Comment by kismp123** [comment]
Thanks you!
