### ISSUE TITLE
Thread.get_linear_address could also take a numeric selector

### ISSUE THREAD

**Issue by MIvanchev** [MarioVilas/winappdbg#55]
I'm currently doing some x86 disassembly and I stumped upon a situation related to the jump instruction involving a segment (selector) given through a non-symbolic value, i.e. `jmp 0x47:0xff00`. With WinAppDbg, calculating the address through `get_linear_address` requires a symbolic name for the segment register which is then immediately converted to a numeric value before being passed on to `GetThreadSelectorEntry`. It would be therefore useful to be able to specify a numeric value directly. I would submit a patch about it.

**Comment by MarioVilas** [comment]
Sounds great! Just make a pull request when you've got the patch :)
