### ISSUE TITLE
Reference documentation link is only available intermittently

### ISSUE THREAD

**Issue by arizvisa** [MarioVilas/winappdbg#6]
The reference documentation listed in the programming guide hyperlinks(!) to nicely generated docs that're unfortunately hosted on a site with either the most underfunded or the worst admins ever. As a result, the reference documentation's availability is based on whether or not they're able to win at their job. However, according to @sfnet_ops on twitter, their present issue has been re-occurring for quite a bit now and thus hopefulness is at a loss.

The bad link is located here: https://github.com/MarioVilas/winappdbg/blob/master/doc/source/ProgrammingGuide.rst

Which points to http://winappdbg.sourceforge.net/doc/latest/reference/ instead of a locally created winappdbg reference.

**Comment by MarioVilas** [comment]
Yes, Sourceforge is the worst :( I will set up the docs at ReadTheDocs instead.
