### ISSUE TITLE
Module.get_symbol_from_list: local variable 'SymbolStartName' referenced before assignment

### ISSUE THREAD

**Issue by MIvanchev** [MarioVilas/winappdbg#60]
As far as I can tell, the bug is obvious (see [here](https://github.com/MarioVilas/winappdbg/blob/1dce6901bdbd3202a44cf6ee36ac8b748e9a5023/winappdbg/module.py#L602)) and should be easy to fix. I'll see what could be done about it.

**Comment by MarioVilas** [comment]
Looks like it. Unfortunately that function isn't mine, came with a pull request and I've no idea what's it supposed to do. :/

**Comment by MarioVilas** [comment]
The function came from this pull request, this may give a hint to why it's failing: https://github.com/MarioVilas/winappdbg/commit/01d7218bf50eef226fcdee96c3612ea281024ad7

**Comment by MIvanchev** [comment]
Yes, I did some debugging as well, it's trying to find the "tightest" symbol encompassing the address. None seems to be the correct return value in the case of no match, yes. So far so good. The 2 functions of the contribution both look for the "closest" match. The first one considers the symbols' size. If no match is found, the second function ignores the size and just looks for the nearest symbol starting address and takes that. The bug is that if there are no symbols at all in the module, the said error is thrown.

**Comment by MIvanchev** [comment]
Maybe @hardik05 could provide additional info?

**Comment by hardik05** [comment]
i was facing some issue with previous function, so i added  def get_symbol_from_list
this function basically parses symbol file and saves there address and name in a list. then when winappdbg request for a symbol at a address, it first tries the default function -> get_symbol_at_address if its not able to find then it calls get_symbol_from_list.
you can check if symbol file is proper or symbols are there?
lastly you can modify the function to check for None and handle them accordingly.

**Comment by zuypt** [comment]
quick fix for everyone until an offical fix
`    def get_symbol_from_list(self,address):
        found = None
        SymList = {}
        SortedSymList = {}
        f = False
        for (SymbolName, SymbolAddress, SymbolSize) in self.iter_symbols():
            SymList[SymbolAddress] = SymbolName
        SortedSymList = sorted(SymList.items())
        for SymbolAddress,SymbolName in SortedSymList:
            if SymbolAddress <= address:
                f = True 
                SymbolStartAddress = SymbolAddress
                SymbolStartName = SymbolName
            else:
                break
        if f:
            found = (SymbolStartName, SymbolStartAddress, 0)
        return found`
